# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Local Maschine


steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  
- task: VisualStudioTestPlatformInstaller@1
  inputs:
    packageFeedSelector: 'nugetOrg'
    versionSelector: 'latestPreRelease'

- task: InstallTestCompleteAdapter@1
  inputs:
    preferredExecutor: 'TC'
- task: VSTest@3
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: 'C:\Users\ackermanng\Documents\TestComplete 15 Projects\ProjectSuite1\ProjectSuite1.pjs'
    searchFolder: '$(System.DefaultWorkingDirectory)'